<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4 Sesuai</name>
   <tag></tag>
   <elementGuidId>f9367e5e-5d34-4320-a2a6-5711c484726b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yItem-RK6-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yItem-RK6-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f47c164-22d9-4c2b-b0a3-7909969e491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-true css-au9xn6</value>
      <webElementGuid>fc1ed1b5-1755-4e47-98f1-b7db788d7a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yItem-RK6-5</value>
      <webElementGuid>3ee26d1e-3c5b-4028-8c76-d2c686994fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yItem-RK6-5&quot;)</value>
      <webElementGuid>a58f0d6c-e5d2-4247-80a7-073ba4f90b15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='yItem-RK6-5']</value>
      <webElementGuid>175f4eac-1ff4-46c7-978a-dbd892f4879f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='talita-container']/div/div[3]/div[4]/div[6]</value>
      <webElementGuid>e131e45e-d268-4a8d-88b5-34ab35ee9a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instruksi'])[1]/following::div[42]</value>
      <webElementGuid>9c8cbd69-76b1-4db2-9ec4-7fdbf1ec85e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[13]</value>
      <webElementGuid>3ceb4bf3-fc75-4c08-ab62-148eda15f578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[13]</value>
      <webElementGuid>57b48cee-7533-4aff-8c8f-7acfb5461877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[6]</value>
      <webElementGuid>e31e171d-82cc-4389-a5a9-92909d14b12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'yItem-RK6-5']</value>
      <webElementGuid>16129300-4f62-4e1d-89c1-a72a606676da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
