<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5 Sesuai</name>
   <tag></tag>
   <elementGuidId>f6cde565-6764-48de-81c2-a8576672269f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yItem-TPK1-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yItem-TPK1-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2b20318e-a342-4481-abea-8ec9d82ea7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-true css-au9xn6</value>
      <webElementGuid>4a10afd6-b6e6-4190-9d86-3204b26e84a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yItem-TPK1-5</value>
      <webElementGuid>fed321ab-0676-4a8e-be13-c633ce374350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yItem-TPK1-5&quot;)</value>
      <webElementGuid>2ec92112-6086-45f1-a448-16aee55c9157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='yItem-TPK1-5']</value>
      <webElementGuid>945a4130-7199-4286-ad44-faf1b6df0e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='talita-container']/div/div[3]/div[5]/div[6]</value>
      <webElementGuid>8b8dcdde-ca56-4852-a786-ff100636daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instruksi'])[1]/following::div[50]</value>
      <webElementGuid>e6c63e71-fbb9-42e7-806c-9abe78b04188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[5]</value>
      <webElementGuid>cff10cdc-6b1f-4eaf-82ed-159ff8629309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[5]</value>
      <webElementGuid>4ab45c79-eaea-4605-95e0-d3a4affd8176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[6]</value>
      <webElementGuid>bd093b5c-714f-4119-a17d-0482e5e395b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'yItem-TPK1-5']</value>
      <webElementGuid>8cfc01ba-979d-42ed-b2ec-b603fab8b51e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
