<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Domisili KAB. MAJALENGKA</name>
   <tag></tag>
   <elementGuidId>62685bd2-083e-418b-81a2-4512e0b60f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cities-option-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='cities-option-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8ca6b6b9-baf6-481b-850c-77b62470491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba60fd87-6086-4be5-b5a4-91dabd78bbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9c5d37ac-9c9f-40d1-a89c-40b4362f5f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cities-option-9</value>
      <webElementGuid>da07d4c4-352a-42bc-8077-d3c361476221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b51b33a5-e533-4273-a16a-941c82572440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>10dedd35-5b61-46a3-a3d4-450fb52a4569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5e33530-21f7-459d-b1ce-cdb519c9edd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>7ad23619-c975-4059-9145-e897bde16857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KAB. MAJALENGKA</value>
      <webElementGuid>87b9241d-2fb5-4a13-8c2b-1d364d0d50de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cities-option-9&quot;)</value>
      <webElementGuid>5253fd01-9c8e-4455-b4df-5cdff258a53b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='cities-option-9']</value>
      <webElementGuid>f7298d0f-75b7-4477-ab9d-4b12ef9bdfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cities-listbox']/li[10]</value>
      <webElementGuid>1b2c39d9-8a60-4407-880d-81ca63a11e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAB. CIREBON'])[1]/following::li[1]</value>
      <webElementGuid>bb8fe18a-cd8b-4619-be50-2399ca3ec954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAB. KUNINGAN'])[1]/following::li[2]</value>
      <webElementGuid>ea7eb9e8-50c5-4f8e-b7a7-37b7818b6f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAB. SUMEDANG'])[1]/preceding::li[1]</value>
      <webElementGuid>74f35b39-e71f-481c-afff-3bfdc8bca832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAB. INDRAMAYU'])[1]/preceding::li[2]</value>
      <webElementGuid>41a3456b-8017-4a96-9b68-807f97162efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KAB. MAJALENGKA']/parent::*</value>
      <webElementGuid>2980f53b-c567-4eb7-a64a-edce84879b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]</value>
      <webElementGuid>95e39cb5-7c63-4ee2-9319-6dfc1746112f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'cities-option-9' and (text() = 'KAB. MAJALENGKA' or . = 'KAB. MAJALENGKA')]</value>
      <webElementGuid>9d3b3e8b-e6ec-40a3-8a95-3b39a1b1a5bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
