<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Drag me to my target</name>
   <tag></tag>
   <elementGuidId>9b1d2bb1-17d5-4c2a-bf35-4dc89b5af634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='draggable']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>57551ad2-e3bf-4da9-aa2d-2df37b24b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag me to my target</value>
      <webElementGuid>f0b44f55-665c-4109-be62-58c5c8d3eb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;draggable&quot;)/p[1]</value>
      <webElementGuid>b4e78e69-3ba1-48df-8911-3ae96073ff9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DnD/Page_Droppable  jQuery UI/iframe_Visual feedback_demo-frame</value>
      <webElementGuid>effeef97-c488-453b-9701-c33128d3e442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggable']/p</value>
      <webElementGuid>b4a0dca7-60fc-43bd-a3a6-da39faca5114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'draggable', '&quot;', ')/p[1]')])[1]/preceding::p[2]</value>
      <webElementGuid>2648a1c1-aee9-4a7a-be87-c4e5636f83e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drag me to my target']/parent::*</value>
      <webElementGuid>b16cd4b3-7725-422b-8dc5-130b3c0a5c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>68c05ddb-5ad5-4d77-9321-61d82fdd6351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Drag me to my target' or . = 'Drag me to my target')]</value>
      <webElementGuid>b461f824-f898-488f-98b3-ead9ee2dcc04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
