<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilihan</name>
   <tag></tag>
   <elementGuidId>467540ec-dcf0-44aa-8f51-c27891587a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdownDetailBatch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownDetailBatch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>436e17b7-6404-4d42-92dc-fda1ffc1b0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-sm dropdown-toggle</value>
      <webElementGuid>7fb18bfd-1d89-4e26-be08-d76b105d627c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69426c0c-3af5-4590-9110-bea74c0dc114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownDetailBatch</value>
      <webElementGuid>6a35058a-df54-498a-a407-3ededa1a2f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>bc131214-b961-49d0-bf29-c3347597eeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b672800c-acea-4e98-a229-4a1c2c18142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7c2cce27-2494-47df-8ce9-0837f5660cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilihan</value>
      <webElementGuid>f72b6977-ad79-427d-a6c0-5d4591e4d830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batchesBody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/center[1]/div[@class=&quot;dropdown&quot;]/button[@id=&quot;dropdownDetailBatch&quot;]</value>
      <webElementGuid>c5c75b0c-473f-4d21-b3f9-2d363ba931d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownDetailBatch']</value>
      <webElementGuid>f5f87ad9-ac76-475d-a13a-1033451232f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='batchesBody']/tr/td[7]/center/div/button</value>
      <webElementGuid>333ee872-2d1a-4918-a38a-8821315fb80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staging Sembilan'])[1]/following::button[1]</value>
      <webElementGuid>a4c87113-4276-407c-8154-4d1163a31f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAULINE'])[1]/following::button[1]</value>
      <webElementGuid>f2945c21-3abf-4e87-8672-43a3ab344e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progress'])[1]/preceding::button[1]</value>
      <webElementGuid>28253505-5f69-41c7-a946-8b2c85a08aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[1]/preceding::button[1]</value>
      <webElementGuid>ad2aaf93-40c9-40d5-8a72-211f6130b15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilihan']/parent::*</value>
      <webElementGuid>e21b0f1d-eef9-4ded-a9d5-4e42487b6fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/div/button</value>
      <webElementGuid>3c66ac6a-fda8-46ed-b819-36f4575d9df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownDetailBatch' and (text() = 'Pilihan' or . = 'Pilihan')]</value>
      <webElementGuid>c1178959-9b98-4b19-9da8-4f8691990365</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
