<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PAULI</name>
   <tag></tag>
   <elementGuidId>e7fec538-fc47-4232-9851-e8722736279f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.font-weight-bold.text-nowrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='userBatchesBody']/tr/td[7]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f0934bb-de77-4be2-83a1-a242e1877216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/report/pauli/1817/21608</value>
      <webElementGuid>077af2a6-d9a8-4742-aba8-f9e5e4e53f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item font-weight-bold text-nowrap</value>
      <webElementGuid>48c73a65-83ca-4959-9f77-f9c7bd03318c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAULI</value>
      <webElementGuid>9af1a3f5-8f6d-43c0-93fa-3bd9b9d4183b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userBatchesBody&quot;)/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/div[@class=&quot;dropdown show open&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/a[@class=&quot;dropdown-item font-weight-bold text-nowrap&quot;]</value>
      <webElementGuid>dc748ae9-ed23-47f6-becb-3812b04da3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='userBatchesBody']/tr/td[7]/div/div/div/div/a</value>
      <webElementGuid>fdc14598-2edf-486b-8551-996b5c4a230f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PAULI')]</value>
      <webElementGuid>e875fbbe-6ddc-49f9-8786-1545cdf147a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[3]/following::a[1]</value>
      <webElementGuid>1acd27ff-ae1b-46fa-94a9-994b1247c973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[3]/following::a[1]</value>
      <webElementGuid>b04c5a4e-e849-46de-b13b-18cf8b73ede8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memproses...'])[1]/preceding::a[2]</value>
      <webElementGuid>68bf9f23-e4c4-4859-afa1-b8a7a6c9ca49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan 1 ke 1 dari 1 entri'])[1]/preceding::a[2]</value>
      <webElementGuid>02ead9d3-aa15-4643-a9c0-21e20321539b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/report/pauli/1817/21608')]</value>
      <webElementGuid>dc9bf310-49b0-4c1a-9909-2acfa38cad5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/a</value>
      <webElementGuid>07f3adac-3805-42fe-b9ed-de7303790286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/report/pauli/1817/21608' and (text() = 'PAULI' or . = 'PAULI')]</value>
      <webElementGuid>53cd0e2e-cd31-410e-90a6-a0d941284bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
