<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4 Sangat Sesuai</name>
   <tag></tag>
   <elementGuidId>96c471e3-91bc-488b-aeb6-e519bafd0eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yItem-RK1-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yItem-RK1-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31ade078-3e7f-4aa0-ac5c-f44065b79de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-true css-au9xn6</value>
      <webElementGuid>51daa44d-0b7f-45de-808b-01cd01927ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yItem-RK1-6</value>
      <webElementGuid>4e4e28ff-18b3-47b9-8815-02536a3ee178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yItem-RK1-6&quot;)</value>
      <webElementGuid>a6e72074-3950-4a20-8d44-660ca3b5482a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='yItem-RK1-6']</value>
      <webElementGuid>420570da-3b60-4be5-a0d4-ec2fd2843fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='talita-container']/div/div[3]/div[4]/div[7]</value>
      <webElementGuid>8dd69e3b-963f-4bbc-aba8-6d62bd8a83e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instruksi'])[1]/following::div[43]</value>
      <webElementGuid>00dab1e8-f08c-4a75-9243-26aafc0c6801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[12]</value>
      <webElementGuid>760c6e08-f645-48fd-97b1-283feb22f31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[12]</value>
      <webElementGuid>290642ab-e359-4d5b-af92-cd635ac0bda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[7]</value>
      <webElementGuid>529e2109-a949-4003-bbef-c8f367a88ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'yItem-RK1-6']</value>
      <webElementGuid>31e40beb-ca8b-4e2c-81fe-b65d88567650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
