<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Orang lain mengandalkan keahlian dan keterampilan yang saya miliki</name>
   <tag></tag>
   <elementGuidId>76b3a2ac-1865-46e3-9cb6-eaf7f1b7d878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Dnd_border1__isGrf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnd-container']/div/div/ul/div/li[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d35d6c9-7d08-49f2-9389-d4446137b77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dnd_border1__isGrf</value>
      <webElementGuid>8b6ffed1-d774-4f51-8575-ee116844eff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnd-container&quot;)/div[1]/div[@class=&quot;Dnd_container1__ygxR8&quot;]/ul[@class=&quot;Dnd_dragList__gQOY_&quot;]/div[1]/li[2]/div[@class=&quot;MuiPaper-root MuiPaper-outlined MuiPaper-rounded css-1cy6rd&quot;]/div[@class=&quot;Dnd_border1__isGrf&quot;]</value>
      <webElementGuid>2d93e7e4-3654-465d-be3a-633ab1acf0ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnd-container']/div/div/ul/div/li[2]/div/div</value>
      <webElementGuid>70409298-008d-4f29-a982-326f132bf4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div</value>
      <webElementGuid>ed8d5ad5-886d-4d0c-a97e-7709a7c16ab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
