<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Self Assessment (Default)</name>
   <tag></tag>
   <elementGuidId>ba42eedd-8966-4f08-8551-0ef5d4e3cb5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#self-assessment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='self-assessment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ecaaf0d-413e-4a51-9f82-436f5c08d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>56c7d1e5-fa4a-4441-a014-a76fad0f28ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/batches/creates-v2</value>
      <webElementGuid>682445a7-b71c-4f0d-9dde-9b757cab1fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>self-assessment</value>
      <webElementGuid>1649910d-a20a-4a06-b0db-e098cacff60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self Assessment (Default)</value>
      <webElementGuid>606a55fe-c978-48c2-9d9d-beea0be5f41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;self-assessment&quot;)</value>
      <webElementGuid>fa1784fe-ed98-4282-81e9-2f52258cebc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f456fb3-28cd-401a-aa22-f07a432a88f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>474029f3-7a2e-4b65-af63-3d809ffead8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/batches/creates-v2</value>
      <webElementGuid>8cbc5781-3c6c-4c03-9697-ada40da2035f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>self-assessment</value>
      <webElementGuid>29a0a1fc-a953-43e2-bd90-5e8c0dba1601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self Assessment (Default)</value>
      <webElementGuid>56646c99-b30f-41be-ba7a-de09fa194cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;self-assessment&quot;)</value>
      <webElementGuid>fe3633dd-b3e7-49e9-9f8b-23b96214cb64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='self-assessment']</value>
      <webElementGuid>3d086f32-a320-4c0e-be1b-5d42624bb8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Self Assessment (Default)')]</value>
      <webElementGuid>d59f7868-5abf-4749-ab71-6cc9387ad9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch Baru'])[1]/following::a[1]</value>
      <webElementGuid>c0bdc27a-a71f-4107-8432-8caed72533ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>9bd02e97-b3c5-47cb-828b-70ec8fdffac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vania'])[1]/preceding::a[1]</value>
      <webElementGuid>08a5a103-af70-4e2a-8fae-e53e905e94d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trisa'])[1]/preceding::a[2]</value>
      <webElementGuid>c291ee2c-fbc8-47c7-a488-13e70921cb25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Self Assessment (Default)']/parent::*</value>
      <webElementGuid>2c39411a-4bee-4128-9971-4cba5deb7239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/batches/creates-v2')]</value>
      <webElementGuid>8bdc6434-9126-4dc2-9a8c-26ed5d4d6d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>623243dd-e0bb-44b5-a6d8-142af3ab518e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/batches/creates-v2' and @id = 'self-assessment' and (text() = 'Self Assessment (Default)' or . = 'Self Assessment (Default)')]</value>
      <webElementGuid>bb14fb72-46ce-487b-9d08-480e9d0a1b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
