<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Seorang pengusaha</name>
   <tag></tag>
   <elementGuidId>e2c02720-f750-4a54-a0ed-88e3014d2fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Dnd_border0__6QLHi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dnd-container']/div/div/ul/div/li/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46ab7487-22d0-4b60-8ba1-91c4531ff20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Dnd_border0__6QLHi</value>
      <webElementGuid>3fe2f8b2-27e7-4769-b602-013653fdaa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dnd-container&quot;)/div[1]/div[@class=&quot;Dnd_container1__ygxR8&quot;]/ul[@class=&quot;Dnd_dragList__gQOY_&quot;]/div[1]/li[1]/div[@class=&quot;MuiPaper-root MuiPaper-outlined MuiPaper-rounded css-1cy6rd&quot;]/div[@class=&quot;Dnd_border0__6QLHi&quot;]</value>
      <webElementGuid>e5e2a564-f5e2-457f-9603-bfb71f4461fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dnd-container']/div/div/ul/div/li/div/div</value>
      <webElementGuid>ceb9c7c8-7abd-4868-ae1c-c85f401c8702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>a9e439f1-d491-42e7-a986-d3644e225a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
