<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Lanjutkan</name>
   <tag></tag>
   <elementGuidId>d6a6219c-2744-4b5a-8bdb-128d452d5f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rules-agree-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='rules-agree-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c52a4f4-5d8c-4a0a-b2de-37fa8d901f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium css-ucdq7g</value>
      <webElementGuid>831e9519-c56e-4c53-baee-a46cbc9052e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fde8d204-5b1f-441c-b350-c286e1035a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7088e82b-e2f1-479b-9b1c-3308bb3c59b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rules-agree-confirm</value>
      <webElementGuid>0365d40f-901f-477b-aba4-27602880fa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>4d56197c-b0be-4301-a6f4-2b96999a3222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rules-agree-confirm&quot;)</value>
      <webElementGuid>f15004f2-a877-4cef-9829-58c48a3503f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='rules-agree-confirm']</value>
      <webElementGuid>1ba5e9d4-77a2-42ba-9a0b-753e98612aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rules-container']/div/div[3]/button</value>
      <webElementGuid>0f8da258-7985-42c2-8c69-340e8ad9e047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya menyetujui seluruh tata tertib di atas'])[1]/following::button[1]</value>
      <webElementGuid>d8ce6735-909f-45d0-9110-d698562c17e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tata Tertib Tes'])[1]/following::button[1]</value>
      <webElementGuid>b397db7b-8388-4cbb-8fa4-f1ea87b44b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>703cfa6f-5c59-4c4b-b942-37c3e606fd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>9c844d49-a2fb-4777-8fe6-53035d08fbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>f03ef5c9-f084-48f8-b2f1-96446bc8984f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>019945ae-8bfa-48d5-9804-ab191105eeff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'rules-agree-confirm' and (text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>4f21e0d7-8a4f-4362-a2e9-4d21fbac37f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
