<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox Tata Tertib Test</name>
   <tag></tag>
   <elementGuidId>43a6fc94-d90c-4197-8dd0-d7f50e70f34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rules-agree-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rules-agree-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c2e27e7-9a84-4395-9498-1880d60ca7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>858eb6ac-2970-4f57-bab8-6460a8b61263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rules-agree-checkbox</value>
      <webElementGuid>3e79870f-8a8e-4ff3-8e88-5a1a16daba45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rules</value>
      <webElementGuid>3242283a-d36e-4852-91bc-a3b8cf861420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e9938d4c-fe0e-4c8e-bbef-6632676599a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24a6167e-df2a-4cb2-9d70-a00beac2efee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rules-agree-checkbox&quot;)</value>
      <webElementGuid>80f66ed2-0796-4a81-9feb-478bdbac17c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rules-agree-checkbox']</value>
      <webElementGuid>2e20a4d9-5bbe-4358-9b31-c19b0c7f292a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rules-container']/div/div[2]/label/span/input</value>
      <webElementGuid>f8e4f237-e08c-4046-af01-ba387eabc8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>af7d53cb-a14d-4909-bf06-97acc5bc1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rules-agree-checkbox' and @name = 'rules' and @type = 'checkbox']</value>
      <webElementGuid>e1d1f4a6-5f9f-4d39-98b9-efd9612c3b00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
