<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textarea Feedback</name>
   <tag></tag>
   <elementGuidId>d925fbee-b0df-4dbf-9be3-d71776e115cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='outlined-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>52a9e4d2-dc77-4d9f-b90c-63531d84665d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>0ba35f98-5156-4eca-995c-068ca6197b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>764e9c7c-2c63-4aa6-99af-cbf4a27639f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-textarea</value>
      <webElementGuid>d928bc4b-c4f1-4182-a5a5-536ba25e8f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tuliskan komentar dan saran Anda mengenai platform tes ini...</value>
      <webElementGuid>55290cc5-b8c2-424e-a04f-572f670abaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline css-u36398</value>
      <webElementGuid>cc8fbbeb-a3bb-468e-8a8e-bb4f45505bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-textarea&quot;)</value>
      <webElementGuid>aa1dc761-0a01-4fed-9734-134e27647aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='outlined-textarea']</value>
      <webElementGuid>7e98c048-1b37-4618-8d0f-5b983fce6f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/form/div[2]/div/textarea</value>
      <webElementGuid>3d983305-b339-4329-93eb-69ef06b16d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>641878bb-ce3d-485c-9dab-7b0c4fe9d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'outlined-textarea' and @placeholder = 'Tuliskan komentar dan saran Anda mengenai platform tes ini...']</value>
      <webElementGuid>ed887c5a-d7dd-4c1c-8d63-55ed5f7d5ef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
