<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>cf81d3c2-89e8-4ce9-b835-1868f0242ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.actionBox.opt02.btnNext.rounded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allButton']/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>104f2572-ba32-4600-ac64-394170fdbffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>24ac588b-c59c-4951-b101-cfdb24bec1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary actionBox opt02 btnNext rounded</value>
      <webElementGuid>b2f7ae63-b333-4741-948d-91926c14dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>a6952177-bfc5-4230-ae93-337788b2257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allButton&quot;)/div[@class=&quot;text-right&quot;]/a[@class=&quot;btn btn-primary actionBox opt02 btnNext rounded&quot;]</value>
      <webElementGuid>8fda9d69-ee23-433f-b65c-c89db4ec0f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abceb2bb-c111-4afc-937d-5e7164e774f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8fc86b8a-e1dd-4857-95bb-034ba372004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary actionBox opt02 btnNext rounded</value>
      <webElementGuid>39e6f7af-2f27-4937-954e-483fd410a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>7a07f54e-905d-4675-b3ff-8978b4cd4666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allButton&quot;)/div[@class=&quot;text-right&quot;]/a[@class=&quot;btn btn-primary actionBox opt02 btnNext rounded&quot;]</value>
      <webElementGuid>6873c0f4-6a37-4cf0-a8c2-0213e9032715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allButton']/div/a[2]</value>
      <webElementGuid>bc194f76-9f53-4d8d-a868-aa8dfe4d1edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lanjutkan')]</value>
      <webElementGuid>5f1773c5-6656-4e29-a6b8-7371c59759d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sisa FUP Harian'])[1]/following::a[2]</value>
      <webElementGuid>401a97a5-3bf6-4b8c-bd64-0764862a0000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Pemotongan'])[1]/following::a[2]</value>
      <webElementGuid>73dcb099-7184-4f77-809c-de74180506ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan Template Pengaturan'])[1]/preceding::a[3]</value>
      <webElementGuid>571db7d5-d4e3-4c64-92a7-98cee35c6a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Template'])[1]/preceding::a[3]</value>
      <webElementGuid>bc30d8b3-e26e-43e6-8c16-b034668eaa49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>f2f1e12a-a242-48b8-a7ab-a0c6c3760766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>af227dfb-dcdc-4fd2-9fc8-90e7c4ce4a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/a[2]</value>
      <webElementGuid>d0b16657-94b1-4e7d-ac47-8cac964363bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>3335bb37-b61d-41e4-a71b-1f29f533a7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
