<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Batch_batchName</name>
   <tag></tag>
   <elementGuidId>9435a6de-9f3e-4381-9354-af410e92bf3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#batchName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='batchName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c301ca3e-a00e-4f64-9fc7-ddbc9cff1d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3aa0606-b3a4-4ad1-8fce-9032a7aee13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>380a20e7-c53e-41a9-ab4e-b89fe0a069f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>batchName</value>
      <webElementGuid>f85b1a2b-01e2-49bc-8c34-3c89ab82e8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: HR Manager 2020</value>
      <webElementGuid>07f962b3-3380-46f6-bfde-9ad4021af45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batchName&quot;)</value>
      <webElementGuid>34dece00-5de9-41bc-a1e3-0a31f5151589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96a9c4aa-316f-4732-a396-5434748a3428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c267a301-a51e-4b09-a1c5-8106f9789378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d9863c6c-12c4-4fd6-b061-3b091802ed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>batchName</value>
      <webElementGuid>ccec8d19-8512-4f93-af92-0a38df2fe7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: HR Manager 2020</value>
      <webElementGuid>903720f0-e1a9-430e-9ea7-914be8bde451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;batchName&quot;)</value>
      <webElementGuid>052f22a8-7ae6-4eb4-861c-462cdbe9d6b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='batchName']</value>
      <webElementGuid>2687e1f4-ea89-45de-9f88-7eda98b0defd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-settingAsesmen']/div/div/div/input</value>
      <webElementGuid>e2e32777-a57a-4c06-bb0e-7e2d8f50d269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>a194f459-efcc-4eb4-bb76-cd07c44da2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'batchName' and @placeholder = 'Contoh: HR Manager 2020']</value>
      <webElementGuid>272e2a8d-6dc5-4915-818f-4d8fe06aef34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
