<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PERSONA_1</name>
   <tag></tag>
   <elementGuidId>15d7267a-a899-4bf7-929f-a0c7a02ab9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-groupTest-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-groupTest-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f67f51f-82cc-459b-a5c6-ff1079487ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>03aa881d-fca5-461c-9c30-21c805e5d0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-groupTest-container</value>
      <webElementGuid>9285bb2d-803f-4b24-ac8e-de7b25be31cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PERSONA</value>
      <webElementGuid>ae0e454f-5cca-4e1e-8f74-b805054f5733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PERSONA</value>
      <webElementGuid>7b244971-e0da-469c-9f6c-ca73be133305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-groupTest-container&quot;)</value>
      <webElementGuid>b04e86aa-7c84-437b-a165-95d94070b48b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-groupTest-container']</value>
      <webElementGuid>3b8d58b7-1eed-44f3-8f58-8111aa45ff47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='create-settingAsesmen']/div/div[2]/span/span/span/span</value>
      <webElementGuid>24749b4a-414a-4db6-8133-23d9ed8a067e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelompok Tes'])[1]/following::span[4]</value>
      <webElementGuid>32086f9b-71f4-40d1-b45a-35134cc71de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empty'])[1]/following::span[4]</value>
      <webElementGuid>aef8d47e-b1e1-4c11-8e75-71737071b0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAI (Learning Agility Index)'])[1]/preceding::span[3]</value>
      <webElementGuid>febc2546-9dec-4afa-a9ce-0848c5575c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TIKI (Tes Inteligensi Kolektif Indonesia)'])[1]/preceding::span[3]</value>
      <webElementGuid>429f6b17-9424-46dd-a9da-a744054904f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>b97d3b47-ec09-4b0b-bee9-99f4fb0ef0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-groupTest-container' and @title = 'PERSONA' and (text() = 'PERSONA' or . = 'PERSONA')]</value>
      <webElementGuid>085a505c-bde2-4692-ac6e-72d25e1aecaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
