<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sangat Sesuai</name>
   <tag></tag>
   <elementGuidId>873965d2-9f43-4253-80aa-76b23c11adca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yItem-OK1-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yItem-OK1-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4620f48-3a8a-42ad-b571-c0490a7a09b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-true css-au9xn6</value>
      <webElementGuid>2eb8d4a5-4637-491e-82d8-5729f7f4bef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yItem-OK1-6</value>
      <webElementGuid>67f25478-acf6-41a7-8d2f-58578763fc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yItem-OK1-6&quot;)</value>
      <webElementGuid>e92593de-f703-4210-8c0e-df3c687bd797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='yItem-OK1-6']</value>
      <webElementGuid>a76d7add-4b18-4e01-8402-943ab8347686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='talita-container']/div/div[3]/div/div[7]</value>
      <webElementGuid>21457945-cff3-4220-9731-901fefeca8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instruksi'])[1]/following::div[19]</value>
      <webElementGuid>4227de54-6fd4-4c39-b15f-1ced9c774a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[36]</value>
      <webElementGuid>37557a11-d3c3-4a9e-a9f5-ab8e2761c128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[36]</value>
      <webElementGuid>203c4a3b-9016-4866-9f68-5c9b44600835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[7]</value>
      <webElementGuid>6a3f1096-dfe2-489b-b375-0b040048612e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'yItem-OK1-6']</value>
      <webElementGuid>70d15957-9d59-4f02-9ae1-99cca4cafc95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
